name: phyid-docs

on: 
    workflow_dispatch:
    push:
        branches:
        - main
    pull_request:

jobs:
  deploy_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install phyid
        run: |
            python -m pip install --upgrade pip
            python -m pip install -e .
      - name: Install doc dependencies
        run: |
            cd docs && python -m pip install -r requirements.txt
      - name: Build the docs
        run: |
            cd docs && make clean html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs/_build/html'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2